# Generated by Django 4.1.1 on 2022-10-16 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "sup_no",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="employee number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=15, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=15, verbose_name="Last name"),
                ),
                ("hire_date", models.DateField(verbose_name="hire date")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_no",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="employee number",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="hire date")),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.supervisor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
