# Generated by Django 4.1.1 on 2022-10-16 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                default="SOME STRING", max_length=15, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                default="SOME STRING", max_length=15, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="supervisor",
            field=models.ForeignKey(
                default=models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.supervisor",
            ),
        ),
    ]
