# Generated by Django 4.1 on 2022-10-13 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0002_rename_appointment_session_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["start_date"]},
        ),
        migrations.RemoveField(
            model_name="session",
            name="reason",
        ),
        migrations.AddField(
            model_name="session",
            name="notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for each session",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACT", "Active"),
                    ("INA", "Inactive"),
                    ("CAN", "Cancelled"),
                    ("FIN", "Finished"),
                ],
                default="INA",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEV", "Development"),
                    ("TRA", "Training"),
                    ("UNG", "Unguided"),
                    ("GUD", "Guided"),
                ],
                default="GUD",
                max_length=3,
            ),
        ),
        migrations.DeleteModel(
            name="SessionReason",
        ),
        migrations.DeleteModel(
            name="SessionStatus",
        ),
        migrations.DeleteModel(
            name="SessionType",
        ),
    ]
