# Generated by Django 4.1.1 on 2022-10-16 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0003_alter_session_options_remove_session_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for each session",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=1000, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
