# Generated by Django 4.1 on 2022-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0006_delete_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="recording",
            field=models.FileField(null=True, upload_to="uploads/videos"),
        ),
    ]
